"""initial migration

Revision ID: 0ad223d5c330
Revises: 
Create Date: 2026-04-21 15:00:03.805807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ad223d5c330'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_transaction_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.add_column('orders', sa.Column('paypal_order_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['transaction_id'])
    op.drop_constraint(op.f('orders_user_email_fkey'), 'orders', type_='foreignkey')
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'payment_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.alter_column('payments', 'payment_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(op.f('orders_user_email_fkey'), 'orders', 'users', ['user_email'], ['email'])
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'paypal_order_id')
    op.create_table('payment_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_transactions_pkey'))
    )
    op.create_index(op.f('ix_payment_transactions_transaction_id'), 'payment_transactions', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    # ### end Alembic commands ###
