"""add stripe_session_id

Revision ID: ffc77f00d781
Revises: dc4aeba4a371
Create Date: 2026-05-06 18:12:41.800335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffc77f00d781'
down_revision: Union[str, Sequence[str], None] = 'dc4aeba4a371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_session_id', sa.String(), nullable=True))
    op.alter_column('webhook_events', 'event_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('webhook_events', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('webhook_events', 'raw_body',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('webhook_events', 'received_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_events', 'received_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('webhook_events', 'raw_body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('webhook_events', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('webhook_events', 'event_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('payments', 'stripe_session_id')
    # ### end Alembic commands ###
